{
 "title": "dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "qa-db-mqtt-ack",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(ack_timestamp/1000,1s),\n  count(id)\nFROM mqtt_ack_time\nWHERE\n  $__unixEpochFilter(ack_timestamp/1000)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "qa-db-mqtt-delivery",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(delivery_timestamp/1000,1s),\n  count(id)\nFROM mqtt_delivery_time\nWHERE\n  $__unixEpochFilter(delivery_timestamp/1000)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "qa-db-mqtt-proc-time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ack_timestamp AS \"time\",\n  proc_time\nFROM mqtt_processing_time\nWHERE\n  $__unixEpochFilter(ack_timestamp/1000)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "qa-db-events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(kfk_timestamp/1000,1s),\n  count(id)\nFROM qaevents\nWHERE\n  $__unixEpochFilter(kfk_timestamp/1000) AND kfk_topic = 'events'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "qa-db-rulecheck",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(kfk_timestamp/1000,1s),\n  count(id) AS \"id\"\nFROM qaevents\nWHERE\n  $__unixEpochFilter(kfk_timestamp/1000) AND kfk_topic = 'rule_check'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "qa-db-proc-time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  dp_in AS \"time\",\n  dp_proc_time\nFROM qatimes\nWHERE\n  $__unixEpochFilter(dp_in/1000)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "qa-db-events-partitions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  kfk_timestamp AS \"time\",\n  kfk_partition\nFROM qaevents\nWHERE\n  $__unixEpochFilter(kfk_timestamp/1000) AND kfk_topic = 'events'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "qa-db-rulecheck-partitions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  kfk_timestamp AS \"time\",\n  kfk_partition\nFROM qaevents\nWHERE\n  $__unixEpochFilter(kfk_timestamp/1000) AND kfk_topic = 'rule_check'\nORDER BY 1"
    }
   ]
  }
 ]
}